### PR TITLE
default.xml: change to use setup-environment-internal

### PR DESCRIPTION
**Pull request by kutenai**
Apply to 2.0 release

### CODE REVIEW

**Comment by koenkooi** [comment]
Same comments as with #47: please reformat the commit message and don't make default.xml executable.

**Comment by kutenai** [comment]
Done

**Comment by koenkooi** [comment]
As with #47: You only changed the title of the pull request, not the commit message. The 0755 change is also still in there.

**Comment by koenkooi** [comment]
This one leads to:
```
OSError: [Errno 2] No such file or directory: '/build/v2015.12/sources/meta-angstrom/setup-environment-internal'
```

I'm not entirely convinced it's worth fixing up release from before 2016. Having said that, my main fileserver at home is still running 2014.06 :/

**Comment by kutenai** [comment]
What are you doing to test these?

**Comment by koenkooi** [comment]
I apply the patch manually, then run ‘repo sync’

**Pull request merged**
