### PR TITLE
default.xml: change to use setup-environment-internal

### PR DESCRIPTION
**Pull request by kutenai**
Apply changes to 2.1 version

### CODE REVIEW

**Comment by koenkooi** [comment]
Like with #47, can you reformat the commit message to be the others? Also, don't make default.xml executable.

**Comment by kutenai** [comment]
Done

**Comment by koenkooi** [comment]
As with #47: You only changed the title of the pull request, not the commit message. The 0755 change is also still in there.

**Comment by koenkooi** [comment]
This one leads to:
```
OSError: [Errno 2] No such file or directory: '/build/v2016.06/layers/meta-angstrom/setup-environment-internal'
```

**Pull request merged**
