### PR TITLE
default.xml: change to use setup-environment-internal

### PR DESCRIPTION
**Pull request by kutenai**
Removed the '../../../' and replace with the 'setup-environment-internal' call, which has been merged already.

### CODE REVIEW

**Comment by koenkooi** [comment]
Can you re-do the commit message to make it look more like other commits, e.g. "default.xml: change to use setup-environment-internal"

**Comment by kutenai** [comment]
Done

**Comment by koenkooi** [comment]
You only changed the title of the pull request, not the title of the commit:
Schermafbeelding 2020-06-04 om 17 09 52

Also, the change to make default.xml 0755 is still in there as well, that needs to get removed.

**Comment by koenkooi** [comment]
This one leads to:
```
Traceback (most recent call last):
  File "/build/v2016.12/.repo/repo/main.py", line 531, in <module>
    _Main(sys.argv[1:])
  File "/build/v2016.12/.repo/repo/main.py", line 507, in _Main
    result = repo._Run(argv) or 0
  File "/build/v2016.12/.repo/repo/main.py", line 180, in _Run
    result = cmd.Execute(copts, cargs)
  File "/build/v2016.12/.repo/repo/subcmds/sync.py", line 821, in Execute
    project.Sync_LocalHalf(syncbuf, force_sync=opt.force_sync)
  File "/build/v2016.12/.repo/repo/project.py", line 1379, in Sync_LocalHalf
    self._CopyAndLinkFiles()
  File "/build/v2016.12/.repo/repo/project.py", line 1287, in _CopyAndLinkFiles
    copyfile._Copy()
  File "/build/v2016.12/.repo/repo/project.py", line 242, in _Copy
    if not os.path.exists(dest) or not filecmp.cmp(src, dest):
  File "/usr/lib/python2.7/filecmp.py", line 42, in cmp
    s1 = _sig(os.stat(f1))
OSError: [Errno 2] No such file or directory: '/build/v2016.12/layers/meta-angstrom/setup-environment-internal'
```

**Comment by kutenai** [comment]
I just started learning about yocto yesterday -- literally.
I do not know if there is a companion repo to update here or what.
I'm not sure how you are testing this either.

**Comment by kutenai** [comment]
I made commits on all 5 branches in meta-angstrom repository. These commits add the missing file `setup-environment-internal` for each of the companion branches.
If you merge those PR's first, then these should all work.

**Pull request merged**
