### PR TITLE
Angstrom v2015.06 yocto1.8

### PR DESCRIPTION
**Pull request by twoerner**

### CODE REVIEW

**Comment by kraj** [comment]
After some thought, I have decided to merge it. Could you also send a patch explaining when bash will be needed ? i.e. when folks dont have dialog or whiptail on there build box.

**Comment by kraj** [comment]
Can you also cherry-pick it for master

**Comment by twoerner** [comment]
I didn't want to cause too much consternation in your project, so when you pointed out the issues with the "select" option, I removed it and force-pushed a new merge request that didn't have it. So what you've merged doesn't have a "select" option -- just the whiptail and dialog options :-)

**Comment by kraj** [comment]
even better

**Pull request merged**
